from __future__ import annotations

import asyncio
import html
import logging
from typing import Any, Iterable

import httpx

from app.schemas import TradeRecommendation
from app.services.simulator import INSTRUMENT_SPECS, normalize_granularity

logger = logging.getLogger(__name__)

TELEGRAM_API = "https://api.telegram.org"
CAPTION_LIMIT = 1024
MESSAGE_LIMIT = 4096
PHOTO_TIMEOUT = 20.0
MAX_RETRIES = 3

MODEL_LABELS = {
    "claude-sonnet-4-5": "Claude Sonnet 4.5",
    "claude-3-7-sonnet-latest": "Claude 3.7 Sonnet",
    "claude-3-5-sonnet-latest": "Claude 3.5 Sonnet",
    "claude-3-5-haiku-latest": "Claude 3.5 Haiku",
    "claude-opus-4-5": "Claude Opus 4.5",
}

_alerted_ids: set[str] = set()


def parse_chat_ids(raw: str | Iterable[str] | None) -> list[str]:
    if raw is None:
        return []
    if isinstance(raw, str):
        parts = raw.replace(";", ",").replace("\n", ",").split(",")
        return [p.strip() for p in parts if p.strip()]
    return [str(p).strip() for p in raw if str(p).strip()]


def model_label(model: str | None) -> str:
    if not model:
        return "FoxAgent ICT engine"
    return MODEL_LABELS.get(model, model)


def _esc(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=False)


def _price(symbol: str, value: float) -> str:
    spec = INSTRUMENT_SPECS.get(symbol, {})
    digits = int(spec.get("decimals", 5))
    return f"{value:,.{digits}f}"


def _tp(rec: TradeRecommendation, level: int) -> str:
    for item in rec.tradeSetup.takeProfitLevels:
        if item.level == level:
            return _price(rec.symbol, item.price)
    return "—"


def _hashtag(symbol: str) -> str:
    return "#" + symbol.replace("/", "").replace("_", "")


def _rationale_block(rec: TradeRecommendation) -> str:
    lines = [rec.rationale.strip()] if rec.rationale else []
    for item in rec.confluence[:5]:
        if item and item not in rec.rationale:
            lines.append(f"• {item}")
    return "\n".join(lines).strip() or "Multi-timeframe ICT confluence."


def format_trade_alert_html(rec: TradeRecommendation, *, caption: bool = False) -> str:
    """Build Telegram HTML. Caption mode stays within the 1024-char photo limit."""
    limit = CAPTION_LIMIT if caption else MESSAGE_LIMIT
    action = rec.tradeSetup.action.value if hasattr(rec.tradeSetup.action, "value") else str(rec.tradeSetup.action)
    order = rec.tradeSetup.orderType.value if hasattr(rec.tradeSetup.orderType, "value") else str(rec.tradeSetup.orderType)
    rr = rec.tradeSetup.riskRewardRatio
    header = (
        f"<b>🚨 FOXAGENT NEW TRADE SETUP 🚨</b>\n"
        f"━━━━━━━━━━━━━━━━━━━━\n"
        f"📊 Asset: {_esc(_hashtag(rec.symbol))} ({_esc(rec.timeframe)})\n"
        f"🎯 Action: <b>{_esc(action)}</b> ({_esc(order)})\n"
        f"⚖️ Risk / Reward: 1:{_esc(f'{rr:.1f}')}\n"
        f"\n"
        f"📍 Entry Price: <code>{_esc(_price(rec.symbol, rec.tradeSetup.entryPrice))}</code>\n"
        f"🛑 Stop Loss: <code>{_esc(_price(rec.symbol, rec.tradeSetup.stopLoss))}</code>\n"
        f"🎯 TP1: <code>{_esc(_tp(rec, 1))}</code>\n"
        f"🎯 TP2: <code>{_esc(_tp(rec, 2))}</code>\n"
        f"\n"
        f"🧠 Confluence &amp; Rationale:\n"
    )
    footer = (
        f"\n\n⚡ Generated by: {_esc(model_label(rec.model))}\n"
        f"━━━━━━━━━━━━━━━━━━━━"
    )
    budget = max(80, limit - len(header) - len(footer) - 8)
    rationale = _rationale_block(rec)
    if len(rationale) > budget:
        rationale = rationale[: budget - 1].rstrip() + "…"
    return header + _esc(rationale) + footer


async def _telegram_credentials() -> tuple[str, list[str], bool]:
    from app.services.settings_store import load_runtime_settings

    runtime = await load_runtime_settings()
    token = (runtime.telegramBotToken or "").strip()
    chats = parse_chat_ids(runtime.telegramChatId)
    enabled = bool(runtime.enableTelegramNotifications)
    return token, chats, enabled


def telegram_ready(token: str, chats: list[str], enabled: bool) -> bool:
    return bool(enabled and token and chats)


async def _post_with_retry(
    client: httpx.AsyncClient,
    url: str,
    *,
    data: dict[str, Any] | None = None,
    files: dict[str, Any] | None = None,
) -> httpx.Response:
    last_exc: Exception | None = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = await client.post(url, data=data, files=files, timeout=PHOTO_TIMEOUT)
            if resp.status_code in {429, 500, 502, 503, 504} and attempt < MAX_RETRIES:
                wait = min(8.0, 0.6 * (2 ** (attempt - 1)))
                retry_after = resp.headers.get("Retry-After")
                if retry_after:
                    try:
                        wait = min(8.0, float(retry_after))
                    except ValueError:
                        pass
                logger.warning("Telegram HTTP %s, retrying in %.1fs", resp.status_code, wait)
                await asyncio.sleep(wait)
                continue
            return resp
        except (httpx.TimeoutException, httpx.TransportError) as exc:
            last_exc = exc
            if attempt >= MAX_RETRIES:
                raise
            wait = min(8.0, 0.6 * (2 ** (attempt - 1)))
            logger.warning("Telegram transport error (%s), retrying in %.1fs", exc, wait)
            await asyncio.sleep(wait)
    raise last_exc or RuntimeError("Telegram request failed")


async def send_trade_alert(
    trade_data: TradeRecommendation | dict[str, Any],
    chart_image_bytes: bytes | None = None,
    *,
    token: str | None = None,
    chat_ids: str | list[str] | None = None,
    enabled: bool | None = None,
) -> dict[str, Any]:
    rec = (
        trade_data
        if isinstance(trade_data, TradeRecommendation)
        else TradeRecommendation.model_validate(trade_data)
    )
    if token is None or chat_ids is None or enabled is None:
        stored_token, stored_chats, stored_enabled = await _telegram_credentials()
        token = token if token is not None else stored_token
        chats = parse_chat_ids(chat_ids) if chat_ids is not None else stored_chats
        enabled = stored_enabled if enabled is None else enabled
    else:
        chats = parse_chat_ids(chat_ids)

    if not telegram_ready(token or "", chats, bool(enabled)):
        logger.debug("Telegram alert skipped (disabled or missing credentials)")
        return {"ok": False, "skipped": True, "detail": "Telegram disabled or not configured"}

    caption = format_trade_alert_html(rec, caption=True)
    if len(caption) > CAPTION_LIMIT:
        caption = caption[: CAPTION_LIMIT - 1] + "…"
    text = format_trade_alert_html(rec, caption=False)

    results: list[dict[str, Any]] = []
    async with httpx.AsyncClient() as client:
        for chat_id in chats:
            item: dict[str, Any] = {"chat_id": chat_id}
            try:
                if chart_image_bytes:
                    url = f"{TELEGRAM_API}/bot{token}/sendPhoto"
                    resp = await _post_with_retry(
                        client,
                        url,
                        data={"chat_id": chat_id, "caption": caption, "parse_mode": "HTML"},
                        files={"photo": ("foxagent-setup.png", chart_image_bytes, "image/png")},
                    )
                    if resp.status_code >= 400:
                        logger.warning("sendPhoto failed (%s), falling back to sendMessage", resp.text[:180])
                        url = f"{TELEGRAM_API}/bot{token}/sendMessage"
                        resp = await _post_with_retry(
                            client,
                            url,
                            data={
                                "chat_id": chat_id,
                                "text": text,
                                "parse_mode": "HTML",
                                "disable_web_page_preview": True,
                            },
                        )
                else:
                    url = f"{TELEGRAM_API}/bot{token}/sendMessage"
                    resp = await _post_with_retry(
                        client,
                        url,
                        data={
                            "chat_id": chat_id,
                            "text": text,
                            "parse_mode": "HTML",
                            "disable_web_page_preview": True,
                        },
                    )
                payload = resp.json() if resp.headers.get("content-type", "").startswith("application/json") else {}
                item["ok"] = resp.status_code < 400 and bool(payload.get("ok", True))
                item["status"] = resp.status_code
                if not item["ok"]:
                    item["detail"] = str(payload.get("description") or resp.text)[:240]
            except Exception as exc:
                logger.warning("Telegram send failed for %s: %s", chat_id, exc)
                item["ok"] = False
                item["detail"] = str(exc)
            results.append(item)

    ok = any(r.get("ok") for r in results)
    return {"ok": ok, "skipped": False, "results": results}


async def send_test_ping(token: str, chat_id: str) -> dict[str, Any]:
    token = (token or "").strip()
    chats = parse_chat_ids(chat_id)
    if not token:
        return {"ok": False, "detail": "TELEGRAM_BOT_TOKEN is required"}
    if not chats:
        return {"ok": False, "detail": "TELEGRAM_CHAT_ID is required"}
    text = (
        "<b>🦊 FoxAgent Telegram link is live.</b>\n"
        "Trade alerts will include ICT overlay chart snapshots when a setup is generated."
    )
    try:
        async with httpx.AsyncClient() as client:
            resp = await _post_with_retry(
                client,
                f"{TELEGRAM_API}/bot{token}/sendMessage",
                data={
                    "chat_id": chats[0],
                    "text": text,
                    "parse_mode": "HTML",
                    "disable_web_page_preview": True,
                },
            )
        payload = resp.json() if resp.headers.get("content-type", "").startswith("application/json") else {}
        if resp.status_code < 400 and payload.get("ok", True):
            extra = f" (+{len(chats) - 1} more chat)" if len(chats) > 1 else ""
            return {"ok": True, "detail": f"Test message delivered to {chats[0]}{extra}"}
        return {"ok": False, "detail": str(payload.get("description") or resp.text)[:240]}
    except Exception as exc:
        return {"ok": False, "detail": str(exc)}


async def render_recommendation_snapshot(rec: TradeRecommendation) -> bytes | None:
    try:
        from app.services.chart_capture import render_candles_png
        from app.services.oanda import oanda

        gran = normalize_granularity(rec.timeframe)
        candles = await oanda.get_candles(rec.symbol, gran, 220)
        if not candles:
            return None
        title = f"{rec.symbol.replace('_', '/')}  {rec.timeframe}  ·  {rec.tradeSetup.action} {rec.tradeSetup.orderType}"
        return render_candles_png(candles, title, rec.klineOverlays, width=1400, height=788)
    except Exception as exc:
        logger.warning("Chart snapshot for Telegram failed: %s", exc)
        return None


async def dispatch_trade_alert(rec: TradeRecommendation) -> dict[str, Any]:
    token, chats, enabled = await _telegram_credentials()
    if not telegram_ready(token, chats, enabled):
        logger.debug("Telegram dispatcher idle — notifications off or secrets missing")
        return {"ok": False, "skipped": True, "detail": "Telegram disabled or not configured"}
    image = await render_recommendation_snapshot(rec)
    return await send_trade_alert(rec, image, token=token, chat_ids=chats, enabled=enabled)


def schedule_trade_alert(rec: TradeRecommendation) -> None:
    """Fire-and-forget so SSE / WebSocket clients are never blocked."""
    if rec.id in _alerted_ids:
        logger.debug("Telegram alert already queued for %s", rec.id)
        return
    _alerted_ids.add(rec.id)
    if len(_alerted_ids) > 500:
        _alerted_ids.clear()
        _alerted_ids.add(rec.id)

    async def _runner() -> None:
        try:
            result = await dispatch_trade_alert(rec)
            if result.get("skipped"):
                return
            if result.get("ok"):
                logger.info("Telegram trade alert sent for %s", rec.id)
            else:
                logger.warning("Telegram trade alert incomplete for %s: %s", rec.id, result)
        except Exception:
            logger.exception("Telegram background alert crashed for %s", rec.id)

    try:
        loop = asyncio.get_running_loop()
        loop.create_task(_runner())
    except RuntimeError:
        logger.debug("No running event loop; Telegram alert not scheduled")


def reset_alert_dedupe() -> None:
    _alerted_ids.clear()
